### ISSUE TITLE
Microsoft.Azure.DigitalTwins.Parser upgrade to latest ?

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/device-models-tools#185]
The DMR client is still using a old v3 of Microsoft.Azure.DigitalTwins.Parser. Can we have this upgraded to the latest version. https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/6.0.0-preview

@rido-min

**Comment by rido-min** [comment]
May I ask which features are you missing from the 3.x release ?

**Comment by sourabhkrishna** [comment]
Was trying to play around with DTDL v3 preview and 3.x threw parsing error "Unsupported Context". The vs code extensions and Az IoT Explorer seems to support v3 context through. @rido-min

**Comment by sourabhkrishna** [comment]
Any updates on this support?

**Comment by rido-min** [comment]
Once the DTDL v3 language specification, and the DTDL v3 parser are released (not-preview), we will evaluate the plan to start accepting DTDL v3 models in this repository.

**Comment by sourabhkrishna** [comment]
Any tentative dates of v3 release ?
