### ISSUE TITLE
can we use this tool to generate IoT Central style model that IoT Central needs

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/device-models-tools#186]
Can I use **expand** command to generate the JSON array single model that IoT Central needs? If Not, can you add this feature to the tool, i found it is useful for user to test the local multi-component model before they submit to github (or they do not want to submit)

**IoT Central expects the JSON file to contain the device model with the interfaces defined inline, rather than in separate files**,

**Comment by rido-min** [comment]
Hi @xiongyu0523 ,  Central accepts the "expanded" form, by having all the interfaces in a JSON array.

What do you mean with "giant model" ?

**Comment by xiongyu0523** [comment]
Yes, it is the format that IoT Central expect to accept. Can we use dmr-client with some parameters to generate this file instead of multiple interfaces seperately?

**Comment by rido-min** [comment]
yes, `dmr-client export` will create a single file with an array of all dependent interfaces.

**Comment by xiongyu0523** [comment]
cool, sorry for misunderstanding of expand & export..let's close
