### ISSUE TITLE
DTDL v3 support in dmr-client

### ISSUE THREAD

**Issue by bernardpletikosa** [Azure/device-models-tools#206]
Hi,

[DTDL v3 is in GA](https://azure.microsoft.com/en-us/updates/generally-available-azure-digital-twins-supports-digital-twins-definition-language-version-3/) and it can be used in ADT.

We are using [dmr-client](https://github.com/Azure/iot-plugandplay-models-tools/tree/dev/clients/dotnet/Microsoft.IoT.ModelsRepository.CommandLine#usage-of-dmr-client) to validate models before uploading them to ADT instances and in general to help with development and make sure nothing broken is merged.
Is there a date when we can expect dmr-client to support DTDL v3?

P.S. Question originally posted on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/1330357/dtdl-v3-support-in-tooling)

**Comment by digimaun** [comment]
Hey @bernardpletikosa,

The latest `dmr-client` should already support DTDL v3.  There is a `--max-dtdl-version` parameter where you can specify the desired max DTDL support level. It currently defaults to `2`.

For example:

`dmr-client validate --max-dtdl-version 3 --model-file /path/to/model.json`

Let us know if this resolves the issue.
